services:
  api:
    build: .
    ports:
      - "${HOST_PORT:-3000}:3000"
    environment:
      - PORT=3000
      - HOST_PORT=${HOST_PORT:-3000}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_KEY=${API_KEY}
    restart: unless-stopped
